name: Build flappy bird

on: workflow_dispatch

jobs:
  flappy-bird:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metadata
        id: gen_meta
        run: |
          SHORTHASH=$(git rev-parse --short HEAD)
          echo "**** Setting build date to $BUILD_DATE ****"
          echo ::set-output name=sub_sha::${SHORTHASH}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: |
            ghcr.io/Forestierr/flappy-bird
          labels: |
            org.opencontainers.image.title=flappy-bird
            org.opencontainers.image.description="https://github.com/Forestierr/dai-flappy-bird"
            org.opencontainers.image.vendor=Forestierr
            org.opencontainers.image.source="https://github.com/Forestierr/dai-flappy-bird"
            org.opencontainers.image.version="${{ steps.gen_meta.outputs.sub_sha }}"
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.gen_meta.outputs.sub_sha }}
          flavor: |
            prefix=flappy-bird,onlatest=true  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Forestierr
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ghcr.io/forestierr/flappy-bird:latest